### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
We've decided on a change of strategy: rather than start from scratch and import JSON-API things, we're going to start from a clone of the digital-asset/daml repo and remove things. I've force-pushed the current main of the daml repo to the main of this repo.

**Comment by ray-roestenburg-da** [comment]
It's still open @garyverhaegen-da ?

**Comment by garyverhaegen-da** [comment]
> It's still open @garyverhaegen-da ?

Ys I've rebased and reopened. I realized it still makes sense to change the README :-)

**Comment by ray-roestenburg-da** [comment]
Ah of course

**Review by ray-roestenburg-da — APPROVED** [review]

**Pull request merged**
